// This file serves as a common location for all your action constants

export enum ActionTypes {
    CONNECT_SUCCESSFUL = "CONNECT_SUCCESSFUL",
    CONNECT_FAILED = "CONNECT_FAILED",
    LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL",
    LOGIN_FAILED = "LOGIN_FAILED",
    SOMETHING_HAPPENED_SUCCESSFULLY = "SOMETHING_HAPPENED_SUCCESSFULLY",
    SOMETHING_FAILED = "SOMETHING_FAILED",
    UPDATE_APICLIENT = "UPDATE_APICLIENT",
}
